name: String2024 Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - develop

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert line endings for gradlew
        run: dos2unix gradlew

      - name: Ensure gradlew has execute permission
        run: chmod +x gradlew

      - name: Copy application.yml
        run: cp /home/mschoi/Desktop/tourismContest/String-BE/application.yml ./src/main/resources/application.yml

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy JAR file to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -P 30022 build/libs/*.jar \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/mschoi/Desktop/tourismContest/String-BE/app.jar

      - name: Run deploy.sh remotely
        run: |
          echo "Running Blue/Green deploy script..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} -p 30022 \
            "bash /home/mschoi/Desktop/tourismContest/String-BE/deploy.sh"

      - name: Show latest backend logs
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} -p 30022 \
            "tail -n 100 /home/mschoi/Desktop/tourismContest/String-BE/logs/app_*.log"

      - name: Clean up unused Docker images (optional)
        run: docker image prune -f
